# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xuandongz/bm3d_src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xuandongz/bm3d_src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xuandongz/bm3d_src/CMakeFiles /home/xuandongz/bm3d_src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xuandongz/bm3d_src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bm3d

# Build rule for target.
bm3d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bm3d
.PHONY : bm3d

# fast build rule for target.
bm3d/fast:
	$(MAKE) -f CMakeFiles/bm3d.dir/build.make CMakeFiles/bm3d.dir/build
.PHONY : bm3d/fast

# target to build an object file
bm3d.o:
	$(MAKE) -f CMakeFiles/bm3d.dir/build.make CMakeFiles/bm3d.dir/bm3d.o
.PHONY : bm3d.o

# target to preprocess a source file
bm3d.i:
	$(MAKE) -f CMakeFiles/bm3d.dir/build.make CMakeFiles/bm3d.dir/bm3d.i
.PHONY : bm3d.i

# target to generate assembly for a file
bm3d.s:
	$(MAKE) -f CMakeFiles/bm3d.dir/build.make CMakeFiles/bm3d.dir/bm3d.s
.PHONY : bm3d.s

# target to build an object file
io_png.o:
	$(MAKE) -f CMakeFiles/bm3d.dir/build.make CMakeFiles/bm3d.dir/io_png.o
.PHONY : io_png.o

# target to preprocess a source file
io_png.i:
	$(MAKE) -f CMakeFiles/bm3d.dir/build.make CMakeFiles/bm3d.dir/io_png.i
.PHONY : io_png.i

# target to generate assembly for a file
io_png.s:
	$(MAKE) -f CMakeFiles/bm3d.dir/build.make CMakeFiles/bm3d.dir/io_png.s
.PHONY : io_png.s

# target to build an object file
lib_transforms.o:
	$(MAKE) -f CMakeFiles/bm3d.dir/build.make CMakeFiles/bm3d.dir/lib_transforms.o
.PHONY : lib_transforms.o

# target to preprocess a source file
lib_transforms.i:
	$(MAKE) -f CMakeFiles/bm3d.dir/build.make CMakeFiles/bm3d.dir/lib_transforms.i
.PHONY : lib_transforms.i

# target to generate assembly for a file
lib_transforms.s:
	$(MAKE) -f CMakeFiles/bm3d.dir/build.make CMakeFiles/bm3d.dir/lib_transforms.s
.PHONY : lib_transforms.s

# target to build an object file
main.o:
	$(MAKE) -f CMakeFiles/bm3d.dir/build.make CMakeFiles/bm3d.dir/main.o
.PHONY : main.o

# target to preprocess a source file
main.i:
	$(MAKE) -f CMakeFiles/bm3d.dir/build.make CMakeFiles/bm3d.dir/main.i
.PHONY : main.i

# target to generate assembly for a file
main.s:
	$(MAKE) -f CMakeFiles/bm3d.dir/build.make CMakeFiles/bm3d.dir/main.s
.PHONY : main.s

# target to build an object file
mt19937ar.o:
	$(MAKE) -f CMakeFiles/bm3d.dir/build.make CMakeFiles/bm3d.dir/mt19937ar.o
.PHONY : mt19937ar.o

# target to preprocess a source file
mt19937ar.i:
	$(MAKE) -f CMakeFiles/bm3d.dir/build.make CMakeFiles/bm3d.dir/mt19937ar.i
.PHONY : mt19937ar.i

# target to generate assembly for a file
mt19937ar.s:
	$(MAKE) -f CMakeFiles/bm3d.dir/build.make CMakeFiles/bm3d.dir/mt19937ar.s
.PHONY : mt19937ar.s

# target to build an object file
utilities.o:
	$(MAKE) -f CMakeFiles/bm3d.dir/build.make CMakeFiles/bm3d.dir/utilities.o
.PHONY : utilities.o

# target to preprocess a source file
utilities.i:
	$(MAKE) -f CMakeFiles/bm3d.dir/build.make CMakeFiles/bm3d.dir/utilities.i
.PHONY : utilities.i

# target to generate assembly for a file
utilities.s:
	$(MAKE) -f CMakeFiles/bm3d.dir/build.make CMakeFiles/bm3d.dir/utilities.s
.PHONY : utilities.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... bm3d"
	@echo "... edit_cache"
	@echo "... bm3d.o"
	@echo "... bm3d.i"
	@echo "... bm3d.s"
	@echo "... io_png.o"
	@echo "... io_png.i"
	@echo "... io_png.s"
	@echo "... lib_transforms.o"
	@echo "... lib_transforms.i"
	@echo "... lib_transforms.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mt19937ar.o"
	@echo "... mt19937ar.i"
	@echo "... mt19937ar.s"
	@echo "... utilities.o"
	@echo "... utilities.i"
	@echo "... utilities.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

